apiVersion: v1
kind: Service
metadata:
  name: gateway-test
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30002
    - name: lp1
      protocol: TCP
      port: 30033
      targetPort: 30033
      nodePort: 30033
    - name: lp2
      protocol: TCP
      port: 30034
      targetPort: 30034
      nodePort: 30034
    - name: lp3
      protocol: TCP
      port: 30035
      targetPort: 30035
      nodePort: 30035
    - name: lp4
      protocol: TCP
      port: 30036
      targetPort: 30036
      nodePort: 30036
    - name: prom
      port: 9898
      targetPort: 9898
      nodePort: 31199
      protocol: TCP
  selector:
    app: gateway-test
  type: NodePort
