apiVersion: v1
kind: Service
metadata:
  name: gateway-master-service
spec:
  ports:
    - name: admin
      protocol: TCP
      port: 9736
      targetPort: 9736
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: keycloak
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: keycloakadmin
      protocol: TCP
      port: 9990
      targetPort: 9990
  selector:
    app: gateway-master
  type: NodePort
