apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - name: db
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
    type: LoadBalancer
    externalIPs:
      - 192.168.103.52
      - 192.168.103.53
      - 192.168.103.54
